name: OnlineMonitor
version: 0.5.0
main: com.vogulev.online_monitor.OnlineMonitorPlugin
api-version: "1.20"
author: Vogulev
description: Advanced online monitoring system with detailed statistics

commands:
  online:
    description: Shows online statistics
    usage: /<command> [stats|top|player|help]

permissions:
  onlinemonitor.*:
    description: All plugin permissions
    children:
      onlinemonitor.basic: true
      onlinemonitor.stats: true
      onlinemonitor.admin: true

  onlinemonitor.basic:
    description: Basic /online command
    default: true

  onlinemonitor.stats:
    description: Access to extended statistics
    default: true

  onlinemonitor.admin:
    description: Admin permissions
    default: op
